### ISSUE TITLE
Llm question

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [Jeomon/Web-Agent#1]
Hi, just found out about this and I'm hyped! I noticed the lack of documentation in the readme regarding which LLM is used and other configuration. Do you use litellm? Openrouter? I recommend both!

**Comment by Jeomon** [comment]
I currently use Groq and Gemini as my main models due to their strong performance. At the moment, LLMs are accessed via direct API calls to the respective providers.

While I don’t use LiteLLM or OpenRouter currently, I’m considering integrating them in the future. I'll update the documentation to clarify these details—thanks again for bringing this up!

**Comment by thiswillbeyourgithub** [comment]
Thanks. While I'm at it I ddn't know what a11y was and had to look it up. Personally I think it would be worth making the first mention a link to https://www.a11yproject.com

Edit : just saw it's sort of explained at the top

**Comment by thiswillbeyourgithub** [comment]
Just to clarify : i recommend using the litellm python library to handle model requests. That way when a new model comes out it's super easy to switch. You can also make it use ollama easily. It can call openrouter so people who don't have tons of api keys can still use it!
